// header menu navigate
export const NAVIGATE_CATEGORY = 'NAVIGATE_CATEGORY';

// get category/post/comment
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_DONE = 'GET_CATEGORY_DONE';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_DONE = 'GET_ALL_POSTS_DONE';
export const GET_POST_DETAIL = 'GET_POST_DETAIL';
export const GET_POST_DETAIL_DONE = 'GET_POST_DETAIL_DONE';

// update/delete post
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_DONE = 'DELETE_POST_DONE';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_DONE = 'UPDATE_POST_DONE';

// new/update/delete comment
export const NEW_COMMENT = 'NEW_COMMENT';
export const NEW_COMMENT_DONE = 'NEW_COMMENT_DONE';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_DONE = 'UPDATE_COMMENT_DONE';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_DONE = 'DELETE_COMMENT_DONE';

// vote
export const LIKE_THE_POST = 'LIKE_THE_POST';
export const LIKE_THE_POST_DONE = 'LIKE_THE_POST_DONE';
export const LIKE_THE_COMMENT = 'LIKE_THE_COMMENT';
export const LIKE_THE_COMMENT_DONE = 'LIKE_THE_COMMENT_DONE';
export const DISLIKE_THE_POST = 'DISLIKE_THE_POST';
export const DISLIKE_THE_POST_DONE = 'DISLIKE_THE_POST_DONE';
export const DISLIKE_THE_COMMENT = 'DISLIKE_THE_COMMENT';
export const DISLIKE_THE_COMMENT_DONE = 'DISLIKE_THE_COMMENT_DONE';
