export const ADD_TEST = 'ADD_TEST';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_DONE = 'GET_CATEGORY_DONE';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_DONE = 'GET_ALL_POSTS_DONE';
export const NAVIGATE_CATEGORY = 'NAVIGATE_CATEGORY';